-- Cria tabela sentiment_analysis usada pela entidade SentimentAnalysisEntity

CREATE TABLE sentiment_analysis (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_text CLOB NOT NULL,
  model_type  VARCHAR2(100) NOT NULL,
  prediction  VARCHAR2(100) NOT NULL,
  probability NUMBER(12,8) NOT NULL,
  lang    VARCHAR2(20),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_sentiment_analysis_created_at ON sentiment_analysis (created_at);
